// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type Room struct {
	Code string
}

func RoomActive(room Room) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div style=\"\r\n                display:flex;\r\n                flex-direction:column;\r\n                height:100vh;\r\n                background:#f5f5f5;\r\n            \"><!-- ROOM HEADER WITH CODE --><div style=\"\r\n                    background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);\r\n                    padding:15px 20px;\r\n                    display:flex;\r\n                    justify-content:space-between;\r\n                    align-items:center;\r\n                    box-shadow:0 2px 8px rgba(0,0,0,0.1);\r\n                \"><h2 style=\"\r\n                        color:white;\r\n                        margin:0;\r\n                        font-size:1.5em;\r\n                    \">🎬 <p>Room Name</p></h2><div style=\"\r\n                        display:flex;\r\n                        align-items:center;\r\n                        gap:15px;\r\n                    \"><div style=\"\r\n                            background:rgba(255,255,255,0.2);\r\n                            padding:8px 16px;\r\n                            border-radius:8px;\r\n                            display:flex;\r\n                            align-items:center;\r\n                            gap:10px;\r\n                        \"><span style=\"\r\n                                color:white;\r\n                                font-size:0.9em;\r\n                                font-weight:bold;\r\n                            \">Room Code:</span> <span id=\"roomCodeDisplay\" style=\"\r\n                                color:white;\r\n                                font-size:1.3em;\r\n                                font-weight:bold;\r\n                                letter-spacing:2px;\r\n                                font-family:monospace;\r\n                            \">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(room.Code)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `GOTTH/cmd/Templ/components/RoomActive.templ`, Line: 74, Col: 39}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span></div><button type=\"button\" onclick=\"copyRoomCode()\" style=\"\r\n                            background:white;\r\n                            color:#667eea;\r\n                            border:none;\r\n                            padding:8px 16px;\r\n                            border-radius:6px;\r\n                            cursor:pointer;\r\n                            font-weight:bold;\r\n                            transition:all 0.3s ease;\r\n                        \" onmouseover=\"this.style.background='#f0f0f0'\" onmouseout=\"this.style.background='white'\">📋 Copy Code</button> <button type=\"button\" hx-get=\"/\" hx-target=\"body\" hx-swap=\"innerHTML\" style=\"\r\n                            background:rgba(255,255,255,0.2);\r\n                            color:white;\r\n                            border:2px solid white;\r\n                            padding:8px 16px;\r\n                            border-radius:6px;\r\n                            cursor:pointer;\r\n                            font-weight:bold;\r\n                            transition:all 0.3s ease;\r\n                        \" onmouseover=\"this.style.background='rgba(255,255,255,0.3)'\" onmouseout=\"this.style.background='rgba(255,255,255,0.2)'\">🏠 Home</button></div></div><!-- VIDEO PLAYER CONTENT --><div style=\"\r\n                    flex:1;\r\n                    overflow:auto;\r\n                \">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = VideoPlayerContent(room.Code).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div><script>\r\n            function copyRoomCode() {\r\n                const code = document.getElementById('roomCodeDisplay').textContent;\r\n                navigator.clipboard.writeText(code).then(() => {\r\n                    alert('Room code copied to clipboard!');\r\n                }).catch(() => {\r\n                    alert('Failed to copy room code');\r\n                });\r\n            }\r\n        </script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base("Room - GoTTH").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
