// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type Room struct {
	Code string
}

func RoomActive(room Room) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div style=\"\n                display:flex;\n                flex-direction:column;\n                height:100vh;\n                background:#f5f5f5;\n            \"><!-- ROOM HEADER WITH CODE --><div style=\"\n                    background:#000;\n                    padding:16px 20px;\n                    display:flex;\n                    justify-content:space-between;\n                    align-items:center;\n                    border-bottom:1px solid #e0e0e0;\n                \"><div><p style=\"color:#999; font-size:0.85em; margin-bottom:4px;\">Room Code</p><span id=\"roomCodeDisplay\" style=\"\n                            color:white;\n                            font-size:1.4em;\n                            font-weight:600;\n                            letter-spacing:3px;\n                            font-family:monospace;\n                        \">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(room.Code)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/Templ/components/RoomActive.templ`, Line: 40, Col: 35}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span></div><div style=\"display:flex; gap:8px;\"><button type=\"button\" onclick=\"copyRoomCode()\" style=\"\n                            background:#333;\n                            color:white;\n                            border:none;\n                            padding:8px 16px;\n                            border-radius:4px;\n                            cursor:pointer;\n                            font-size:0.9em;\n                            font-weight:500;\n                            transition:all 0.2s;\n                        \" onmouseover=\"this.style.background='#444'\" onmouseout=\"this.style.background='#333'\">Copy</button> <button type=\"button\" hx-get=\"/\" hx-target=\"body\" hx-swap=\"innerHTML\" style=\"\n                            background:#f5f5f5;\n                            color:#000;\n                            border:1px solid #e0e0e0;\n                            padding:8px 16px;\n                            border-radius:4px;\n                            cursor:pointer;\n                            font-size:0.9em;\n                            font-weight:500;\n                            transition:all 0.2s;\n                        \" onmouseover=\"this.style.background='#efefef'\" onmouseout=\"this.style.background='#f5f5f5'\">Home</button></div></div><!-- VIDEO PLAYER CONTENT --><div style=\"\n                    flex:1;\n                    overflow:auto;\n                \">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = VideoPlayerContent(room.Code).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div><script>\n            function copyRoomCode() {\n                const code = document.getElementById('roomCodeDisplay').textContent;\n                navigator.clipboard.writeText(code).then(() => {\n                    alert('Room code copied to clipboard!');\n                }).catch(() => {\n                    alert('Failed to copy room code');\n                });\n            }\n        </script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base("Room - GoTTH").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
